# 创建数组

In [1]:
import numpy as np

In [2]:
arr1=np.array([0.3,0.5,4.2])
arr2=np.array([[3,4,5],[4,2,1]])
print(arr1)
print(arr2)
print(type(arr1))

[0.3 0.5 4.2]
[[3 4 5]
 [4 2 1]]
<class 'numpy.ndarray'>


In [3]:
#查看数组的基本属性
print(arr1.shape)
print(arr1.ndim)
print(arr1.dtype)
print(arr2.shape)
print(arr2.ndim)
print(arr2.dtype)

(3,)
1
float64
(2, 3)
2
int64


In [4]:
#初识数组的特点
list1=[0.3,0.5,4.2]
arr1=np.array([0.3,0.5,4.2])
print(list1)
print(arr1)

# list1 ** 2
print([i**2 for i in list1])
arr1 ** 2

[0.3, 0.5, 4.2]
[0.3 0.5 4.2]
[0.09, 0.25, 17.64]


array([ 0.09,  0.25, 17.64])

In [5]:
arr3=np.arange(0,10)
print(arr3)
#起点默认等于0
arr4=np.arange(10)
print(arr4)
arr5=np.arange(0,1,0.1)
print(arr5)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [6]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : integer or real, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : integer or real
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off 

In [7]:
arr6=np.linspace(0,1,11)
#生成等差数组
print(arr6)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [8]:
#利用zeros函数创建数组
arr7=np.zeros([3,4,5])
print(arr7)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [9]:
#数组的数据类型
arr8=np.array([3,4,5],dtype=np.float64)#创建数组时，声明起数据类型
print(arr8)
print(arr8.dtype)

arr8[0]=1.2
print(arr8)
print(np.int64(arr8))#转换数组的数据类型

[3. 4. 5.]
float64
[1.2 4.  5. ]
[1 4 5]


In [10]:
#生成随机数
print(np.random.random(10))  #无约束条件下的随机数
print(np.random.rand(3,4))   #生成指定shape的均匀分布的随机数
print(np.random.randn(10))   #生成服从指定shape的正态分布的随机数

[0.79710914 0.42164295 0.00471608 0.90180962 0.14543386 0.78440472
 0.65429753 0.8551308  0.76307446 0.00687179]
[[0.38377332 0.22144068 0.13936082 0.9364113 ]
 [0.66486017 0.8719312  0.56926188 0.48079059]
 [0.4579212  0.6023793  0.3136965  0.97950115]]
[ 0.55707014 -1.60193359 -0.17519289 -2.0996548   0.66539571 -0.0682692
 -1.06092206 -0.68329469 -0.61674806 -0.20748816]


In [11]:
#数组的索引
arr1=np.array([0.3,0.78,0.24,5,3.2])
print(arr1)
print(arr1[0])  #一维数组单个元素的索引
print(arr1[-5])

#一维数组的多个元素的索引(切片)
print(arr1[1:3]) #左开右闭
print(arr1[-4:-2])

res1=arr1[3]
res2=arr1[3:4]
print(res1,type(res1))
print(res2)

#res1和res2返回的类型不一样
print(res1,res1.shape)
print(res2,res2.shape)

[0.3  0.78 0.24 5.   3.2 ]
0.3
0.3
[0.78 0.24]
[0.78 0.24]
5.0 <class 'numpy.float64'>
[5.]
5.0 ()
[5.] (1,)


In [12]:
#逻辑型索引
arr2=np.array([2.3,1.8,4.5])
print(arr2)
print(arr2[[False,False,True]])  #将一个逻辑型的序列传到索引区间里去，根据取值来输出数据
index=arr2 > 2 #将arr2中所有的值与2进行比较，输出判断的值
print(arr2[index]) #将结果放进区间输出,达到对数据的筛选目的

[2.3 1.8 4.5]
[4.5]
[2.3 4.5]


In [13]:
#多维数组的索引
arr3=np.arange(1,13).reshape([3,4])
print(arr3)
print(arr3[2,3])      #根据数据的行号和列号来取出数据
print(arr3[2, 0:])    #取出整行数据，一维数组
print(arr3[:,0])      #取出整列数据，一维数组
print(arr3[1:3,1:3])  #取出指定部分的数据
print(arr3[2:,:])     #取出整行数据，二维数组  注意返回值的shape

print(arr3[arr3[:,0]>4,:])  #二维数组的逻辑性索引

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12
[ 9 10 11 12]
[1 5 9]
[[ 6  7]
 [10 11]]
[[ 9 10 11 12]]
[[ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
#修改数组中的元素
arr3=np.arange(1,13).reshape([3,4])
print(arr3)
arr3[0,0]=15 
print(arr3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[15  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
#求解距离矩阵
n = 10  #样本个数
x = np.linspace(1,100,n)  #样本横坐标
y = np.linspace(1,100,n)  #样本纵坐标

dist=np.zeros([n,n]) #初始距离矩阵

for i in range(n):
    for j in range(n):
        dist[i,j]=np.sqrt((x[i]-x[j])**2+(y[i]-y[j])**2)  #计算欧式距离

print(x)
print(y)
print(dist)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
[[  0.          15.55634919  31.11269837  46.66904756  62.22539674
   77.78174593  93.33809512 108.8944443  124.45079349 140.00714267]
 [ 15.55634919   0.          15.55634919  31.11269837  46.66904756
   62.22539674  77.78174593  93.33809512 108.8944443  124.45079349]
 [ 31.11269837  15.55634919   0.          15.55634919  31.11269837
   46.66904756  62.22539674  77.78174593  93.33809512 108.8944443 ]
 [ 46.66904756  31.11269837  15.55634919   0.          15.55634919
   31.11269837  46.66904756  62.22539674  77.78174593  93.33809512]
 [ 62.22539674  46.66904756  31.11269837  15.55634919   0.
   15.55634919  31.11269837  46.66904756  62.22539674  77.78174593]
 [ 77.78174593  62.22539674  46.66904756  31.11269837  15.55634919
    0.          15.55634919  31.11269837  46.66904756  62.22539674]
 [ 93.33809512  77.78174593  62.22539674  46.66904756  31.11269837
   15.55634919   0.        

In [16]:
#数组形态变化
arr4=np.arange(1,13)
print(arr4)
print(arr4.reshape([3,4]))
print(arr4.reshape([4,3]))

arr5=arr4.reshape([3,4])
print(arr5)
print(arr5.ravel())  #数组展平
arr5.flatten()

arr6=arr4.reshape([3,4])
print(arr6)
np.vstack([arr5,arr6]) #纵向拼接
print(np.hstack((arr5,arr6))) #横向拼接

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  1  2  3  4]
 [ 5  6  7  8  5  6  7  8]
 [ 9 10 11 12  9 10 11 12]]


# 掌握NumPy矩阵与通用函数

## 通用函数： 是一种能够对数组中所有元素进行操作的函数

In [17]:
import numpy as np

In [18]:
matr1=np.mat("1 2 3;4 5 6; 7 8 9")
print(matr1)
print(type(matr1))  #类型是矩阵

matr2=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(matr2)
print(type(matr2))

print(np.bmat('matr1 matr2;matr1 matr2'))  #实现矩阵拼接操作
print(matr1.T) #矩阵的转置
print(matr1.I) #求矩阵的逆

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.matrix'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.matrix'>
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]
 [1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [19]:
#通用函数
arr1=np.array([0.2,0.4,0.6])
arr2=np.array([0.2,0.6,0.78])
list1=[0.2,0.4,0.6]

print(arr1 + 1)
# print(list1 + 1) #非法操作
print(arr1 * 2)
print(list1 * 2) #注意其返回结果是将数组复制了一遍

print(arr1 + arr2) #对应元素相加
print(arr1 * arr2) #对应元素相乘

print(arr1 > 0) #每一个元素都与0做比较
print(arr1 < arr2) #两个数组相比结构需一样

print(np.any(arr1 == 0.2)) #逻辑or
print(np.all(arr1 == 0.2)) #逻辑and

[1.2 1.4 1.6]
[0.4 0.8 1.2]
[0.2, 0.4, 0.6, 0.2, 0.4, 0.6]
[0.4  1.   1.38]
[0.04  0.24  0.468]
[ True  True  True]
[False  True  True]
True
False


In [20]:
#广播机制
arr3=np.arange(1,13).reshape([4,3])
arr4=np.array([1,2,3])
arr5=np.array([[1],[2],[3],[4]])
print(arr3)
print(arr4)
print(arr5)
print(arr3 + arr4)
print(arr3 + arr5)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 2 3]
[[1]
 [2]
 [3]
 [4]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


# 利用NumPy进行统计分析

In [21]:
import numpy as np

In [22]:
arr1=np.arange(1,13).reshape([4,3])
arr2=np.arange(1,13).reshape([3,4])
print(arr1)
print(arr2)

np.save('tmp/arr1.npy',arr1) #保存数据(以二进制方式保存)
arr1_load=np.load('tmp/arr1.npy') #读取数据
print(arr1_load)

np.savez('tmp/arr1&arr2.npz',arr1,arr2) #保存多个数组
arr1_2_load=np.load('tmp/arr1&arr2.npz')
print(arr1_2_load)
print(arr1_2_load.files) #查看数据文件中有哪些数组对象
print(arr1_2_load['arr_0']) #访问数据文件中的具体数组对象

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
['arr_0', 'arr_1']
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [23]:
#读写txt文件
# np.savetxt('tmp/arr1.txt')#以txt形式保存数据
np.savetxt('tmp/arr1.txt',arr1,delimiter=',') #指定以,形式分隔数据
# np.loadtxt('tmp/arr1.txt') #读取数据
np.loadtxt('tmp/arr1.txt',delimiter=',') #读取数据

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [32]:
#使用数组进行简单统计分析
arr3=np.random.randint(1,10,(3,4))
print(arr3)

arr3.sort(axis=0) #对数组元素按大小进行排序
print(arr3)
arr3.argsort(axis=0) #返回排序后的下标
print(arr3)

print(np.tile(arr3,2)) #对数组进行复制操作
print(np.repeat(arr3,2,axis=1)) #对数组与阿奴进行复制

print(arr3.mean()) #统计数组所有元素的均值
print(arr3.mean(axis=0)) #按列统计数组均值
print(arr3.max(axis=0))

print(arr3.argmax(axis=0)) #统计每列元素最大值的位置

[[5 2 6 5]
 [8 6 4 1]
 [8 9 3 1]]
[[5 2 3 1]
 [8 6 4 1]
 [8 9 6 5]]
[[5 2 3 1]
 [8 6 4 1]
 [8 9 6 5]]
[[5 2 3 1 5 2 3 1]
 [8 6 4 1 8 6 4 1]
 [8 9 6 5 8 9 6 5]]
[[5 5 2 2 3 3 1 1]
 [8 8 6 6 4 4 1 1]
 [8 8 9 9 6 6 5 5]]
4.833333333333333
[7.         5.66666667 4.33333333 2.33333333]
[8 9 6 5]
[1 2 2 2]
